### ISSUE TITLE
Docker image is missing the arm arch

### ISSUE THREAD

**Issue by softlion** [valeriansaliou/vigil-local#5]
Docker image is missing the arm arch.  
It contains only the x64 arch.

You could use xbuild to build all archs with github action.  
Any plan on this ?

I have a working example of a [build action](https://github.com/softlion/depin/blob/main/.github/workflows/build-wingbits-docker.yml) and the matching [docker file](https://github.com/softlion/depin/blob/main/wingbits/dockerfile) to do this.

**Comment by softlion** [comment]
I fixed it. Feel free to update your code.

https://hub.docker.com/repository/docker/vapolia/vigil-local

dockerfile:

```dockerfile
FROM scratch

#Automatic args
ARG TARGETARCH
ARG TARGETVARIANT

WORKDIR /usr/local/bin

COPY build/${TARGETARCH}${TARGETVARIANT}/vigil-local/vigil-local .
COPY build/${TARGETARCH}${TARGETVARIANT}/vigil-local/config.cfg /etc/vigil-local.cfg

CMD [ "vigil-local", "-c", "/etc/vigil-local.cfg" ]
```


github action:
```yaml
name: Build Vigil Local Docker Images

on:
  workflow_dispatch:

jobs:
  build-vigil-dockerx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - # Add support for more platforms with QEMU (optional)
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Fetch latest Vigil release version
        run: |
          VERSION=$(curl -s https://api.github.com/repos/valeriansaliou/vigil-local/releases/latest | jq -r .tag_name)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
      
      - name: Download Vigil binaries
        run: |
          mkdir -p build/amd64 build/armv7
          wget -O vigil-local-x86_64.tar.gz "https://github.com/valeriansaliou/vigil-local/releases/download/${VERSION}/${VERSION}-x86_64.tar.gz"
          wget -O vigil-local-armv7.tar.gz "https://github.com/valeriansaliou/vigil-local/releases/download/${VERSION}/${VERSION}-armv7.tar.gz"
          tar -xzf vigil-local-x86_64.tar.gz -C build/amd64 --strip-components=1
          tar -xzf vigil-local-armv7.tar.gz -C build/armv7 --strip-components=1
          
          chmod +x build/amd64/vigil-local/vigil-local build/armv7/vigil-local/vigil-local
          
      - name: Build and push Docker image
        run: |

          cp charts/monitoring/vigil/vigil-local.dockerfile dockerfile

          docker buildx create --use
          docker buildx build --push \
            --platform linux/amd64,linux/arm/v7 \
            -t vapolia/vigil-local:${VERSION} \
            -t vapolia/vigil-local:latest \
            .
```
